### ISSUE TITLE
Trong - FE: Fetch and display Jewelries

### ISSUE THREAD

**Issue by ToLazyToCode** [UpperMoon0/Luci-di-Lusso#1]
Branch: fe/jewelry

Tasks:

- [x]  Update the FE tags to match the enum (with no caplock: Ring, Necklace, etc.)
- [x]  Send request to the BE with the selected tags
- [x]  Display the returned jewelries

Notes:
Send a GET request to http://localhost:8081/product/get-jewelries with a JSON body containing an array of tags for filtering.
The backend will return a list of jewelries that match the provided tags.
If the tag array in the JSON is empty, then the backend will return a list of all jewelries.

Valid tags include:

- RING
- NECKLACE
- BRACELET
- EARRING
- PENDANT
- BROOCH
- MAN
- WOMAN
- CHILDREN
- NEED_SIZING

**Comment by ToLazyToCode** [comment]
all done! Waiting for response

**Comment by UpperMoon0** [comment]
Nice job! Merging to 0.4
